name: Flutter Workflow

on: 
  push:
    branches:
      - infa
      
jobs:
  build:
    name: 🐳 checkbuild
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: "12.x"
      - name: SDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle

      - name: Install Fultter
        uses: flutter-actions/setup-flutter@v2
        with:
         
          flutter-version: "3.7.10"
          channel: 'stable'
          cache: true
  
      - name: Get dependencies
        run: | 
          flutter pub get
          # touch .env
          # echo '' > .env
      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build web

      - name: Run unit tests
        run: flutter test --coverage